export { default as Home } from './home/Home'
export { default as Contact } from './contact/Contact'
export { default as Login } from './Auth/Login'
export { default as Register } from './Auth/Register'
export { default as Reset } from './Auth/Reset'
export { default as Admin } from './admin/Admin'